sonar.projectKey=Theesthan_GiFrac
sonar.organization=eko
sonar.projectName=GiFrac
sonar.projectVersion=1.0
sonar.sources=.
sonar.exclusions=**/*.test.*,**/node_modules/**,**/__pycache__/**,**/.git/**,**/docs/**
sonar.python.version=3.11
